import type { Metadata } from 'next';
import { Geist, Geist_Mono, BBH_Bartle } from 'next/font/google';
import './globals.css';

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

const bbhBartleSans = BBH_Bartle({
	variable: '--font-bbh-bartle-sans',
	weight: '400',
});

export const metadata: Metadata = {
	title: 'Tesseract',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang="en"
			className={`${geistSans.variable} ${geistMono.variable} ${bbhBartleSans.variable} h-full antialiased`}
		>
			<body className="min-h-full flex flex-col">{children}</body>
		</html>
	);
}
